### ISSUE TITLE
Something is wrong with projections

### ISSUE THREAD

**Issue by vsenderov** [treeppl/treeppl#36] opened 2023-11-03 17:05 UTC
I need help with something but I am not sure if it is possible to troubleshoot this.  I suspect might be related to https://github.com/miking-lang/miking-dppl/pull/143, but I am not sure

I have this program https://github.com/vsenderov/qtbirds.tppl

Run:

```
tpplc qtbirds.tppl
./out input.json
```

Will produce:

```
$ ./out input.json
Leaf
Leaf
Leaf
Weighted Leaf, message sequence [1] is
[[ 1 x 4 matrix ]]:
5.65037353072e-05       5.65037353072e-05       0.955407153694  5.65037353072e-05

ERROR <qtbirds.tppl 273:17-273:37>:
Field 'messageSequence' not found
    let mesSeq = tree.messageSequence;
```

As you see it is really weird because the output just before is produced by
```
    printLn("Weighted Leaf, message sequence [1] is");
    printMtx(tree.messageSequence[1]);
```

So, I've no idea...  I am fine if somebody knows a workaround, but this is quite a show-stopper for me in the moment.

**Comment by elegios** [comment] 2023-11-05 10:26
The code generation for field access looks at both field name and type, if one of those falls to match the field is considered not found. Is this Way because I wanted to avoid possible segfaults (this is checked after typechecking, so type errors won’t be detected after it), and it’s possible to have different field types for the same field name across different constructors for the same type, so just erroring if the type is wrong isn’t always the greatest. Most likely it’s caused by using the field as the wrong type. 

All that said, it should be possible, and probably desirable, to produce an error at compile or runtime for this case, since it’s rather confusing.

**Comment by vsenderov** [comment] 2023-11-06 14:28
I think it is a good idea to check both the name and the type.  However, I don't see what would cause the type error here.  I have created here a small example

```
type QTTree =
  | QTLeaf { age: Real
           , index: Int
           , sequence: String
           , character: String
           , stateSequence: Int[]
           , characterState: Int
           }
  | QTNode { left: QTTree
           , right: QTTree
           , age: Real
           }
  | QTWeightedLeaf { age: Real
                   , messageSequence: Tensor[Real][]
                   //, characterMessage: Tensor[Real]
                   , partialLogWeight: Real
                   }
  | QTWeightedNode { left: QTTree
                   , right: QTTree
                   , age: Real
                   , partialLogWeight: Real
                   }
  

model function qtbirds(): Real 
{
  let myVec = rvecCreate(4, [1., 0., 0., 0.]);

  let mySeq = [myVec, myVec, myVec];

  let tree = QTWeightedLeaf { age = 0.0,
                              messageSequence = mySeq,
                              partialLogWeight = log(0.0)
                              };
  
  let x = tree.messageSequence;
  
  printMtx(tree.messageSequence[1]);

  return 1.0;
}
```

The error is 

```
NOTE: Zero-argument function, `qtbirds`, converted to Int. Potential type errors might refer to Int type.
viktor@BDWF26:~/qtbirds.tppl$ ./out input.json 1 1
ERROR <proj-error.tppl 36:10-36:30>:
Field 'messageSequence' not found
  let x = tree.messageSequence;
```

As you can see here, `x` isn't used anywhere, so how could it cause a type error?

What I found is that you need to reconstruct x.  I.e. you need to write:

```
 let x = sapply(tree.messageSequence, tensorId);
```
 
where

```
function tensorId(x: Tensor[Real]) {
  return x;
}
```

Does this make sense?

**Comment by vsenderov** [comment] 2023-11-06 14:31
What also doesn't work is if I try to somehow let the system now that x is of type `Tensor[Real][]` like so:

```
model function qtbirds(): Tensor[Real][] 
{
  let myVec = rvecCreate(4, [1., 0., 0., 0.]);

  let mySeq = [myVec, myVec, myVec];

  let tree = QTWeightedLeaf { age = 0.0,
                              messageSequence = mySeq,
                              partialLogWeight = log(0.0)
                              };
  
  let x = tree.messageSequence; // still doens't work even if we annotated in the function signature

  //let x = sapply(tree.messageSequence, tensorId);

  printMtx(tree.messageSequence[1]);

  return x;
}
```

**Comment by elegios** [comment] 2023-11-06 15:40
The thing that helps here is explicitly annotating the type of `tree.messageSequence`, in this case done in a slightly roundabout way by applying a function that requires a particular type for that parameter.

**Comment by vsenderov** [comment] 2023-11-08 10:55
A random thought. If you introduce _optionals_ would it help us with runtime errors in these variant types?  Like let's say that a field `index` may exist in one constructor but not that in another, that would make it an optional but then all functions that use it need to take care of its missingness?

**Comment by vsenderov** [comment] 2023-12-15 16:52
Do we consider this fully solved now @elegios with your last two PRs or do you still want to improve upon it?

**Comment by elegios** [comment] 2023-12-15 18:36
I think we can probably close it for now, the current implementation should
support most or all of our current use cases, so further improvements can
be a new issue when we start missing it.

**Closed** 2024-01-08 15:26 UTC
